server:
  port: 8002
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/smp666/gitrpo/     # \u914D\u7F6Egit\u4ED3\u5E93\u7684\u5730\u5740
          search-paths: config-repo                             # git\u4ED3\u5E93\u5730\u5740\u4E0B\u7684\u76F8\u5BF9\u5730\u5740\uFF0C\u53EF\u4EE5\u914D\u7F6E\u591A\u4E2A\uFF0C\u7528,\u5206\u5272\u3002
          username:                                        # git\u4ED3\u5E93\u7684\u8D26\u53F7
          password: 
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/   ## \u6CE8\u518C\u4E2D\u5FC3eurka\u5730\u5740